CREATE TABLE `TREE`
(
    `ID`             INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `NODE_NAME`      VARCHAR(100),
    `NODE_TYPE`      VARCHAR(20),
    `NODE_COMMENT`   VARCHAR(255),
    `NODE_PATH`      VARCHAR(255),
    `NODE_INFO`      VARCHAR(1000),
    `PARENT_NODE_ID` INT
);

CREATE TABLE `PROP`
(
    `ID`    INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `KEY`   VARCHAR(255),
    `VALUE` VARCHAR(255)
);
