INSERT INTO TREE (`ID`, `NODE_NAME`, `NODE_TYPE`, `NODE_COMMENT`, `NODE_PATH`, `NODE_INFO`, `PARENT_NODE_ID`)
VALUES (0, 'ROOT', 'ROOT', 'ROOT', '0', null, null);

INSERT INTO PROP (`ID`, `KEY`, `VALUE`)
VALUES (0, 'font.name', '新宋体');
INSERT INTO PROP (`ID`, `KEY`, `VALUE`)
VALUES (1, 'font.size', '14');
INSERT INTO PROP (`ID`, `KEY`, `VALUE`)
VALUES (2, 'font.style', '普通');

INSERT INTO PROP (`ID`, `KEY`, `VALUE`)
VALUES (3, 'K_TOOLS.ID.K_TREE', '1');
INSERT INTO PROP (`ID`, `KEY`, `VALUE`)
VALUES (4, 'K_TOOLS.ID.K_PROP', '5');
